//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gemiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gemiler()
        {
            this.Limanlars = new HashSet<Limanlar>();
        }
    
        public int Id { get; set; }
        public string GemiAd { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<int> ilId { get; set; }
        public Nullable<int> ilceId { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<int> KaptanId { get; set; }
        public Nullable<int> SeferId { get; set; }
    
        public virtual iller iller { get; set; }
        public virtual ilce ilce { get; set; }
        public virtual Kaptan Kaptan { get; set; }
        public virtual Sefer Sefer { get; set; }
        public virtual urunler urunler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Limanlar> Limanlars { get; set; }
    }
}
