//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Limanlar
    {
        public int Id { get; set; }
        public string Limanad { get; set; }
        public Nullable<int> GemilerId { get; set; }
        public Nullable<int> TedarikciLimanId { get; set; }
        public Nullable<int> ilId { get; set; }
        public Nullable<int> ilceId { get; set; }
    
        public virtual Gemiler Gemiler { get; set; }
        public virtual ilce ilce { get; set; }
        public virtual iller iller { get; set; }
        public virtual TedarikciLiman TedarikciLiman { get; set; }
    }
}
