//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LimanOtomEntities1 : DbContext
    {
        public LimanOtomEntities1()
            : base("name=LimanOtomEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Araclar> Araclars { get; set; }
        public virtual DbSet<Depo> Depoes { get; set; }
        public virtual DbSet<Gemiler> Gemilers { get; set; }
        public virtual DbSet<ilce> ilces { get; set; }
        public virtual DbSet<iller> illers { get; set; }
        public virtual DbSet<Kaptan> Kaptans { get; set; }
        public virtual DbSet<Kargo> Kargoes { get; set; }
        public virtual DbSet<KargoSirket> KargoSirkets { get; set; }
        public virtual DbSet<Limanlar> Limanlars { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
        public virtual DbSet<Sefer> Sefers { get; set; }
        public virtual DbSet<SiparisUrun> SiparisUruns { get; set; }
        public virtual DbSet<Sofor> Sofors { get; set; }
        public virtual DbSet<TedarikciLiman> TedarikciLimen { get; set; }
        public virtual DbSet<urunKateg> urunKategs { get; set; }
        public virtual DbSet<urunler> urunlers { get; set; }
    
        public virtual int SP_CreateAraclar(string aracAd, Nullable<bool> aktif, Nullable<int> soforId, Nullable<int> seferId, Nullable<int> ilId, Nullable<int> ilceId)
        {
            var aracAdParameter = aracAd != null ?
                new ObjectParameter("AracAd", aracAd) :
                new ObjectParameter("AracAd", typeof(string));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var soforIdParameter = soforId.HasValue ?
                new ObjectParameter("SoforId", soforId) :
                new ObjectParameter("SoforId", typeof(int));
    
            var seferIdParameter = seferId.HasValue ?
                new ObjectParameter("SeferId", seferId) :
                new ObjectParameter("SeferId", typeof(int));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateAraclar", aracAdParameter, aktifParameter, soforIdParameter, seferIdParameter, ilIdParameter, ilceIdParameter);
        }
    
        public virtual int SP_CreateDepo(Nullable<int> araclarId, Nullable<int> urunlerId)
        {
            var araclarIdParameter = araclarId.HasValue ?
                new ObjectParameter("AraclarId", araclarId) :
                new ObjectParameter("AraclarId", typeof(int));
    
            var urunlerIdParameter = urunlerId.HasValue ?
                new ObjectParameter("urunlerId", urunlerId) :
                new ObjectParameter("urunlerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateDepo", araclarIdParameter, urunlerIdParameter);
        }
    
        public virtual int SP_CreateGemiler(string gemiAd, Nullable<bool> aktif, Nullable<int> ilId, Nullable<int> ilceId, Nullable<int> urunId, Nullable<int> kaptanId, Nullable<int> seferId)
        {
            var gemiAdParameter = gemiAd != null ?
                new ObjectParameter("GemiAd", gemiAd) :
                new ObjectParameter("GemiAd", typeof(string));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("urunId", urunId) :
                new ObjectParameter("urunId", typeof(int));
    
            var kaptanIdParameter = kaptanId.HasValue ?
                new ObjectParameter("KaptanId", kaptanId) :
                new ObjectParameter("KaptanId", typeof(int));
    
            var seferIdParameter = seferId.HasValue ?
                new ObjectParameter("SeferId", seferId) :
                new ObjectParameter("SeferId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateGemiler", gemiAdParameter, aktifParameter, ilIdParameter, ilceIdParameter, urunIdParameter, kaptanIdParameter, seferIdParameter);
        }
    
        public virtual int SP_Createiller(string il)
        {
            var ilParameter = il != null ?
                new ObjectParameter("il", il) :
                new ObjectParameter("il", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Createiller", ilParameter);
        }
    
        public virtual int SP_CreateKaptan(string kaptanAd)
        {
            var kaptanAdParameter = kaptanAd != null ?
                new ObjectParameter("KaptanAd", kaptanAd) :
                new ObjectParameter("KaptanAd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateKaptan", kaptanAdParameter);
        }
    
        public virtual int SP_CreateKargo(Nullable<int> urunlerId, Nullable<int> depoId, Nullable<int> kargoSirketId, Nullable<int> ilId, Nullable<int> ilceId)
        {
            var urunlerIdParameter = urunlerId.HasValue ?
                new ObjectParameter("urunlerId", urunlerId) :
                new ObjectParameter("urunlerId", typeof(int));
    
            var depoIdParameter = depoId.HasValue ?
                new ObjectParameter("DepoId", depoId) :
                new ObjectParameter("DepoId", typeof(int));
    
            var kargoSirketIdParameter = kargoSirketId.HasValue ?
                new ObjectParameter("KargoSirketId", kargoSirketId) :
                new ObjectParameter("KargoSirketId", typeof(int));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateKargo", urunlerIdParameter, depoIdParameter, kargoSirketIdParameter, ilIdParameter, ilceIdParameter);
        }
    
        public virtual int SP_CreateKargoSirket(Nullable<int> sirketAd, Nullable<int> ilId, Nullable<int> ilceId)
        {
            var sirketAdParameter = sirketAd.HasValue ?
                new ObjectParameter("SirketAd", sirketAd) :
                new ObjectParameter("SirketAd", typeof(int));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateKargoSirket", sirketAdParameter, ilIdParameter, ilceIdParameter);
        }
    
        public virtual int SP_CreateLimanlar(string limanad, Nullable<int> gemilerId, Nullable<int> tedarikciLimanId, Nullable<int> ilId, Nullable<int> ilceId)
        {
            var limanadParameter = limanad != null ?
                new ObjectParameter("Limanad", limanad) :
                new ObjectParameter("Limanad", typeof(string));
    
            var gemilerIdParameter = gemilerId.HasValue ?
                new ObjectParameter("GemilerId", gemilerId) :
                new ObjectParameter("GemilerId", typeof(int));
    
            var tedarikciLimanIdParameter = tedarikciLimanId.HasValue ?
                new ObjectParameter("TedarikciLimanId", tedarikciLimanId) :
                new ObjectParameter("TedarikciLimanId", typeof(int));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateLimanlar", limanadParameter, gemilerIdParameter, tedarikciLimanIdParameter, ilIdParameter, ilceIdParameter);
        }
    
        public virtual int SP_CreateMusteri(string musteriAd, string musteriSAd, string tel, string tc, string adres, string ePosta, Nullable<int> ilId, Nullable<int> ilceId)
        {
            var musteriAdParameter = musteriAd != null ?
                new ObjectParameter("MusteriAd", musteriAd) :
                new ObjectParameter("MusteriAd", typeof(string));
    
            var musteriSAdParameter = musteriSAd != null ?
                new ObjectParameter("MusteriSAd", musteriSAd) :
                new ObjectParameter("MusteriSAd", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("Tel", tel) :
                new ObjectParameter("Tel", typeof(string));
    
            var tcParameter = tc != null ?
                new ObjectParameter("Tc", tc) :
                new ObjectParameter("Tc", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var ePostaParameter = ePosta != null ?
                new ObjectParameter("EPosta", ePosta) :
                new ObjectParameter("EPosta", typeof(string));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateMusteri", musteriAdParameter, musteriSAdParameter, telParameter, tcParameter, adresParameter, ePostaParameter, ilIdParameter, ilceIdParameter);
        }
    
        public virtual int SP_CreateSefer(Nullable<int> kalkisSaat, Nullable<int> varisSaat)
        {
            var kalkisSaatParameter = kalkisSaat.HasValue ?
                new ObjectParameter("KalkisSaat", kalkisSaat) :
                new ObjectParameter("KalkisSaat", typeof(int));
    
            var varisSaatParameter = varisSaat.HasValue ?
                new ObjectParameter("VarisSaat", varisSaat) :
                new ObjectParameter("VarisSaat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateSefer", kalkisSaatParameter, varisSaatParameter);
        }
    
        public virtual int SP_CreateSiparisUrun(Nullable<int> urunlerId, Nullable<int> urunKategId, Nullable<int> musteriId, Nullable<int> kargoSirketId, Nullable<int> ilId, Nullable<int> ilceId)
        {
            var urunlerIdParameter = urunlerId.HasValue ?
                new ObjectParameter("urunlerId", urunlerId) :
                new ObjectParameter("urunlerId", typeof(int));
    
            var urunKategIdParameter = urunKategId.HasValue ?
                new ObjectParameter("urunKategId", urunKategId) :
                new ObjectParameter("urunKategId", typeof(int));
    
            var musteriIdParameter = musteriId.HasValue ?
                new ObjectParameter("MusteriId", musteriId) :
                new ObjectParameter("MusteriId", typeof(int));
    
            var kargoSirketIdParameter = kargoSirketId.HasValue ?
                new ObjectParameter("KargoSirketId", kargoSirketId) :
                new ObjectParameter("KargoSirketId", typeof(int));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateSiparisUrun", urunlerIdParameter, urunKategIdParameter, musteriIdParameter, kargoSirketIdParameter, ilIdParameter, ilceIdParameter);
        }
    
        public virtual int SP_CreateTedarikciLiman(string tedarikciFirma, Nullable<int> ilId, Nullable<int> ilceId)
        {
            var tedarikciFirmaParameter = tedarikciFirma != null ?
                new ObjectParameter("TedarikciFirma", tedarikciFirma) :
                new ObjectParameter("TedarikciFirma", typeof(string));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateTedarikciLiman", tedarikciFirmaParameter, ilIdParameter, ilceIdParameter);
        }
    
        public virtual int SP_CreateurunKateg(string kategAd)
        {
            var kategAdParameter = kategAd != null ?
                new ObjectParameter("KategAd", kategAd) :
                new ObjectParameter("KategAd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CreateurunKateg", kategAdParameter);
        }
    
        public virtual int SP_Createurunler(string urunAd, Nullable<int> miktar, Nullable<decimal> fiyat, Nullable<int> urunKategId)
        {
            var urunAdParameter = urunAd != null ?
                new ObjectParameter("urunAd", urunAd) :
                new ObjectParameter("urunAd", typeof(string));
    
            var miktarParameter = miktar.HasValue ?
                new ObjectParameter("Miktar", miktar) :
                new ObjectParameter("Miktar", typeof(int));
    
            var fiyatParameter = fiyat.HasValue ?
                new ObjectParameter("Fiyat", fiyat) :
                new ObjectParameter("Fiyat", typeof(decimal));
    
            var urunKategIdParameter = urunKategId.HasValue ?
                new ObjectParameter("urunKategId", urunKategId) :
                new ObjectParameter("urunKategId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Createurunler", urunAdParameter, miktarParameter, fiyatParameter, urunKategIdParameter);
        }
    
        public virtual int SP_DeleteAraclar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteAraclar", idParameter);
        }
    
        public virtual int SP_DeleteDepo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteDepo", idParameter);
        }
    
        public virtual int SP_DeleteGemiler(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteGemiler", idParameter);
        }
    
        public virtual int SP_Deleteilce(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Deleteilce", idParameter);
        }
    
        public virtual int SP_Deleteiller(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Deleteiller", idParameter);
        }
    
        public virtual int SP_DeleteKaptan(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteKaptan", idParameter);
        }
    
        public virtual int SP_DeleteKargo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteKargo", idParameter);
        }
    
        public virtual int SP_DeleteKargoSirket(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteKargoSirket", idParameter);
        }
    
        public virtual int SP_DeleteLimanlar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteLimanlar", idParameter);
        }
    
        public virtual int SP_DeleteMusteri(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteMusteri", idParameter);
        }
    
        public virtual int SP_DeleteSefer(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteSefer", idParameter);
        }
    
        public virtual int SP_DeleteSiparisUrun(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteSiparisUrun", idParameter);
        }
    
        public virtual int SP_DeleteTedarikciLiman(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteTedarikciLiman", idParameter);
        }
    
        public virtual int SP_DeleteurunKateg(Nullable<int> kategoriId)
        {
            var kategoriIdParameter = kategoriId.HasValue ?
                new ObjectParameter("KategoriId", kategoriId) :
                new ObjectParameter("KategoriId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteurunKateg", kategoriIdParameter);
        }
    
        public virtual int SP_Deleteurunler(Nullable<int> urunId)
        {
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("UrunId", urunId) :
                new ObjectParameter("UrunId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Deleteurunler", urunIdParameter);
        }
    
        public virtual ObjectResult<SP_SelectAraclar_Result> SP_SelectAraclar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAraclar_Result>("SP_SelectAraclar");
        }
    
        public virtual ObjectResult<SP_SelectDepo_Result> SP_SelectDepo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectDepo_Result>("SP_SelectDepo");
        }
    
        public virtual ObjectResult<SP_SelectGemiler_Result> SP_SelectGemiler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectGemiler_Result>("SP_SelectGemiler");
        }
    
        public virtual ObjectResult<SP_Selectilce_Result> SP_Selectilce()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Selectilce_Result>("SP_Selectilce");
        }
    
        public virtual ObjectResult<SP_Selectiller_Result> SP_Selectiller()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Selectiller_Result>("SP_Selectiller");
        }
    
        public virtual ObjectResult<SP_SelectKargo_Result> SP_SelectKargo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectKargo_Result>("SP_SelectKargo");
        }
    
        public virtual ObjectResult<SP_SelectKargoSirket_Result> SP_SelectKargoSirket()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectKargoSirket_Result>("SP_SelectKargoSirket");
        }
    
        public virtual ObjectResult<SP_SelectLimanlar_Result> SP_SelectLimanlar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectLimanlar_Result>("SP_SelectLimanlar");
        }
    
        public virtual ObjectResult<SP_SelectMusteri_Result> SP_SelectMusteri()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectMusteri_Result>("SP_SelectMusteri");
        }
    
        public virtual ObjectResult<SP_SelectSefer_Result> SP_SelectSefer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectSefer_Result>("SP_SelectSefer");
        }
    
        public virtual ObjectResult<SP_SelectSiparisUrun_Result> SP_SelectSiparisUrun()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectSiparisUrun_Result>("SP_SelectSiparisUrun");
        }
    
        public virtual ObjectResult<SP_SelectSofor_Result> SP_SelectSofor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectSofor_Result>("SP_SelectSofor");
        }
    
        public virtual ObjectResult<SP_SelectTedarikciLiman_Result> SP_SelectTedarikciLiman()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectTedarikciLiman_Result>("SP_SelectTedarikciLiman");
        }
    
        public virtual ObjectResult<SP_SelecturunKateg_Result> SP_SelecturunKateg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelecturunKateg_Result>("SP_SelecturunKateg");
        }
    
        public virtual ObjectResult<SP_Selecturunler_Result> SP_Selecturunler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Selecturunler_Result>("SP_Selecturunler");
        }
    
        public virtual int SP_UpdateAraclar(Nullable<int> id, string aracAd, Nullable<bool> aktif, Nullable<int> soforId, Nullable<int> seferId, Nullable<int> ilId, Nullable<int> ilceId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var aracAdParameter = aracAd != null ?
                new ObjectParameter("AracAd", aracAd) :
                new ObjectParameter("AracAd", typeof(string));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var soforIdParameter = soforId.HasValue ?
                new ObjectParameter("SoforId", soforId) :
                new ObjectParameter("SoforId", typeof(int));
    
            var seferIdParameter = seferId.HasValue ?
                new ObjectParameter("SeferId", seferId) :
                new ObjectParameter("SeferId", typeof(int));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateAraclar", idParameter, aracAdParameter, aktifParameter, soforIdParameter, seferIdParameter, ilIdParameter, ilceIdParameter);
        }
    
        public virtual int SP_UpdateDepo(Nullable<int> id, Nullable<int> araclarId, Nullable<int> urunlerId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var araclarIdParameter = araclarId.HasValue ?
                new ObjectParameter("AraclarId", araclarId) :
                new ObjectParameter("AraclarId", typeof(int));
    
            var urunlerIdParameter = urunlerId.HasValue ?
                new ObjectParameter("urunlerId", urunlerId) :
                new ObjectParameter("urunlerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateDepo", idParameter, araclarIdParameter, urunlerIdParameter);
        }
    
        public virtual int SP_UpdateGemiler(Nullable<int> id, string gemiAd, Nullable<bool> aktif, Nullable<int> ilId, Nullable<int> ilceId, Nullable<int> urunId, Nullable<int> kaptanId, Nullable<int> seferId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var gemiAdParameter = gemiAd != null ?
                new ObjectParameter("GemiAd", gemiAd) :
                new ObjectParameter("GemiAd", typeof(string));
    
            var aktifParameter = aktif.HasValue ?
                new ObjectParameter("Aktif", aktif) :
                new ObjectParameter("Aktif", typeof(bool));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("urunId", urunId) :
                new ObjectParameter("urunId", typeof(int));
    
            var kaptanIdParameter = kaptanId.HasValue ?
                new ObjectParameter("KaptanId", kaptanId) :
                new ObjectParameter("KaptanId", typeof(int));
    
            var seferIdParameter = seferId.HasValue ?
                new ObjectParameter("SeferId", seferId) :
                new ObjectParameter("SeferId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateGemiler", idParameter, gemiAdParameter, aktifParameter, ilIdParameter, ilceIdParameter, urunIdParameter, kaptanIdParameter, seferIdParameter);
        }
    
        public virtual int SP_Updateilce(Nullable<int> id, string ilce)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var ilceParameter = ilce != null ?
                new ObjectParameter("ilce", ilce) :
                new ObjectParameter("ilce", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Updateilce", idParameter, ilceParameter);
        }
    
        public virtual int SP_Updateiller(Nullable<int> id, string il)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var ilParameter = il != null ?
                new ObjectParameter("il", il) :
                new ObjectParameter("il", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Updateiller", idParameter, ilParameter);
        }
    
        public virtual int SP_UpdateKaptan(Nullable<int> id, string kaptanAd)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var kaptanAdParameter = kaptanAd != null ?
                new ObjectParameter("KaptanAd", kaptanAd) :
                new ObjectParameter("KaptanAd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateKaptan", idParameter, kaptanAdParameter);
        }
    
        public virtual int SP_UpdateKargo(Nullable<int> id, Nullable<int> urunlerId, Nullable<int> depoId, Nullable<int> kargoSirketId, Nullable<int> ilId, Nullable<int> ilceId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var urunlerIdParameter = urunlerId.HasValue ?
                new ObjectParameter("urunlerId", urunlerId) :
                new ObjectParameter("urunlerId", typeof(int));
    
            var depoIdParameter = depoId.HasValue ?
                new ObjectParameter("DepoId", depoId) :
                new ObjectParameter("DepoId", typeof(int));
    
            var kargoSirketIdParameter = kargoSirketId.HasValue ?
                new ObjectParameter("KargoSirketId", kargoSirketId) :
                new ObjectParameter("KargoSirketId", typeof(int));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateKargo", idParameter, urunlerIdParameter, depoIdParameter, kargoSirketIdParameter, ilIdParameter, ilceIdParameter);
        }
    
        public virtual int SP_UpdateKargoSirket(Nullable<int> id, Nullable<int> sirketAd)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var sirketAdParameter = sirketAd.HasValue ?
                new ObjectParameter("SirketAd", sirketAd) :
                new ObjectParameter("SirketAd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateKargoSirket", idParameter, sirketAdParameter);
        }
    
        public virtual int SP_UpdateLimanlar(Nullable<int> id, string limanad, Nullable<int> gemilerId, Nullable<int> tedarikciLimanId, Nullable<int> ilId, Nullable<int> ilceId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var limanadParameter = limanad != null ?
                new ObjectParameter("Limanad", limanad) :
                new ObjectParameter("Limanad", typeof(string));
    
            var gemilerIdParameter = gemilerId.HasValue ?
                new ObjectParameter("GemilerId", gemilerId) :
                new ObjectParameter("GemilerId", typeof(int));
    
            var tedarikciLimanIdParameter = tedarikciLimanId.HasValue ?
                new ObjectParameter("TedarikciLimanId", tedarikciLimanId) :
                new ObjectParameter("TedarikciLimanId", typeof(int));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateLimanlar", idParameter, limanadParameter, gemilerIdParameter, tedarikciLimanIdParameter, ilIdParameter, ilceIdParameter);
        }
    
        public virtual int SP_UpdateMusteri(Nullable<int> musteriId, string musteriAd, string musteriSAd, string tel, string tc, string adres, string ePosta, Nullable<int> ilId, Nullable<int> ilceId)
        {
            var musteriIdParameter = musteriId.HasValue ?
                new ObjectParameter("MusteriId", musteriId) :
                new ObjectParameter("MusteriId", typeof(int));
    
            var musteriAdParameter = musteriAd != null ?
                new ObjectParameter("MusteriAd", musteriAd) :
                new ObjectParameter("MusteriAd", typeof(string));
    
            var musteriSAdParameter = musteriSAd != null ?
                new ObjectParameter("MusteriSAd", musteriSAd) :
                new ObjectParameter("MusteriSAd", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("Tel", tel) :
                new ObjectParameter("Tel", typeof(string));
    
            var tcParameter = tc != null ?
                new ObjectParameter("Tc", tc) :
                new ObjectParameter("Tc", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var ePostaParameter = ePosta != null ?
                new ObjectParameter("EPosta", ePosta) :
                new ObjectParameter("EPosta", typeof(string));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateMusteri", musteriIdParameter, musteriAdParameter, musteriSAdParameter, telParameter, tcParameter, adresParameter, ePostaParameter, ilIdParameter, ilceIdParameter);
        }
    
        public virtual int SP_UpdateSefer(Nullable<int> id, Nullable<int> kalkisSaat, Nullable<int> varisSaat)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var kalkisSaatParameter = kalkisSaat.HasValue ?
                new ObjectParameter("KalkisSaat", kalkisSaat) :
                new ObjectParameter("KalkisSaat", typeof(int));
    
            var varisSaatParameter = varisSaat.HasValue ?
                new ObjectParameter("VarisSaat", varisSaat) :
                new ObjectParameter("VarisSaat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateSefer", idParameter, kalkisSaatParameter, varisSaatParameter);
        }
    
        public virtual int SP_UpdateSiparisUrun(Nullable<int> id, Nullable<int> urunlerId, Nullable<int> urunKategId, Nullable<int> musteriId, Nullable<int> kargoSirketId, Nullable<int> ilId, Nullable<int> ilceId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var urunlerIdParameter = urunlerId.HasValue ?
                new ObjectParameter("urunlerId", urunlerId) :
                new ObjectParameter("urunlerId", typeof(int));
    
            var urunKategIdParameter = urunKategId.HasValue ?
                new ObjectParameter("urunKategId", urunKategId) :
                new ObjectParameter("urunKategId", typeof(int));
    
            var musteriIdParameter = musteriId.HasValue ?
                new ObjectParameter("MusteriId", musteriId) :
                new ObjectParameter("MusteriId", typeof(int));
    
            var kargoSirketIdParameter = kargoSirketId.HasValue ?
                new ObjectParameter("KargoSirketId", kargoSirketId) :
                new ObjectParameter("KargoSirketId", typeof(int));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateSiparisUrun", idParameter, urunlerIdParameter, urunKategIdParameter, musteriIdParameter, kargoSirketIdParameter, ilIdParameter, ilceIdParameter);
        }
    
        public virtual int SP_UpdateTedarikciLiman(Nullable<int> id, string tedarikciFirma, Nullable<int> ilId, Nullable<int> ilceId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var tedarikciFirmaParameter = tedarikciFirma != null ?
                new ObjectParameter("TedarikciFirma", tedarikciFirma) :
                new ObjectParameter("TedarikciFirma", typeof(string));
    
            var ilIdParameter = ilId.HasValue ?
                new ObjectParameter("ilId", ilId) :
                new ObjectParameter("ilId", typeof(int));
    
            var ilceIdParameter = ilceId.HasValue ?
                new ObjectParameter("ilceId", ilceId) :
                new ObjectParameter("ilceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateTedarikciLiman", idParameter, tedarikciFirmaParameter, ilIdParameter, ilceIdParameter);
        }
    
        public virtual int SP_UpdateurunKateg(Nullable<int> kategoriId, string kategAd)
        {
            var kategoriIdParameter = kategoriId.HasValue ?
                new ObjectParameter("KategoriId", kategoriId) :
                new ObjectParameter("KategoriId", typeof(int));
    
            var kategAdParameter = kategAd != null ?
                new ObjectParameter("KategAd", kategAd) :
                new ObjectParameter("KategAd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateurunKateg", kategoriIdParameter, kategAdParameter);
        }
    
        public virtual int SP_Updateurunler(Nullable<int> urunId, string urunAd, Nullable<int> miktar, Nullable<decimal> fiyat, Nullable<int> urunKategId)
        {
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("UrunId", urunId) :
                new ObjectParameter("UrunId", typeof(int));
    
            var urunAdParameter = urunAd != null ?
                new ObjectParameter("urunAd", urunAd) :
                new ObjectParameter("urunAd", typeof(string));
    
            var miktarParameter = miktar.HasValue ?
                new ObjectParameter("Miktar", miktar) :
                new ObjectParameter("Miktar", typeof(int));
    
            var fiyatParameter = fiyat.HasValue ?
                new ObjectParameter("Fiyat", fiyat) :
                new ObjectParameter("Fiyat", typeof(decimal));
    
            var urunKategIdParameter = urunKategId.HasValue ?
                new ObjectParameter("urunKategId", urunKategId) :
                new ObjectParameter("urunKategId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Updateurunler", urunIdParameter, urunAdParameter, miktarParameter, fiyatParameter, urunKategIdParameter);
        }
    }
}
