//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirportAutomationEntities : DbContext
    {
        public AirportAutomationEntities()
            : base("name=AirportAutomationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airplane> Airplanes { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Expedition> Expeditions { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
