//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketId { get; set; }
        public string NumberOfSeats { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ExpeditionId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> AirplaneId { get; set; }
        public Nullable<int> AirportId { get; set; }
        public Nullable<int> DistrictId { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        public virtual Airport Airport { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual District District { get; set; }
        public virtual Expedition Expedition { get; set; }
    }
}
