// <auto-generated />
namespace Airport.DataEntities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Migrations2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migrations2));
        
        string IMigrationMetadata.Id
        {
            get { return "201911302255416_Migrations2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
